services: 

  postgres: 
    image: postgres:16
    container_name: sfdx_assignment
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-sfdx-assignment}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      POSTGRES_USER: ${DB_USER:-hellomohit}
    ports:
      - "5432:5432"
    volumes:
      - postggres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-enterypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hellomohit"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s